/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_editor_land_new_generator (void)
{
  GtkWidget *editor_land_new_generator;
  GtkWidget *vbox1;
  GtkWidget *Land_start;
  GtkWidget *alignment1;
  GtkWidget *table1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *label1;
  GtkWidget *frame2;
  GtkWidget *alignment2;
  GtkWidget *table2;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *label8;
  GtkWidget *frame3;
  GtkWidget *alignment3;
  GtkWidget *table3;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *label12;
  GtkWidget *button1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  editor_land_new_generator = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (editor_land_new_generator), "New land generator");
  gtk_window_set_default_size (GTK_WINDOW (editor_land_new_generator), 200, -1);
  gtk_window_set_resizable (GTK_WINDOW (editor_land_new_generator), FALSE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (editor_land_new_generator), vbox1);

  Land_start = gtk_frame_new (NULL);
  gtk_widget_show (Land_start);
  gtk_box_pack_start (GTK_BOX (vbox1), Land_start, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (Land_start), 4);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (Land_start), alignment1);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment1), 0, 0, 12, 0);

  table1 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (alignment1), table1);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 5);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 5);

  label2 = gtk_label_new ("X:");
  gtk_widget_show (label2);
  gtk_table_attach (GTK_TABLE (table1), label2, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);

  label3 = gtk_label_new ("Y:");
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (table1), label3, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);

  label4 = gtk_label_new ("Z:");
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table1), label4, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_table_attach (GTK_TABLE (table1), entry1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_table_attach (GTK_TABLE (table1), entry2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_table_attach (GTK_TABLE (table1), entry3, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  label1 = gtk_label_new ("New land start");
  gtk_widget_show (label1);
  gtk_frame_set_label_widget (GTK_FRAME (Land_start), label1);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox1), frame2, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame2), 4);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (frame2), alignment2);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment2), 0, 0, 12, 0);

  table2 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (alignment2), table2);
  gtk_container_set_border_width (GTK_CONTAINER (table2), 5);
  gtk_table_set_row_spacings (GTK_TABLE (table2), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 5);

  label5 = gtk_label_new ("X:");
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table2), label5, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);

  label6 = gtk_label_new ("Y:");
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table2), label6, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);

  label7 = gtk_label_new ("Z:");
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table2), label7, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_table_attach (GTK_TABLE (table2), entry4, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_table_attach (GTK_TABLE (table2), entry5, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_table_attach (GTK_TABLE (table2), entry6, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  label8 = gtk_label_new ("New land block size");
  gtk_widget_show (label8);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label8);
  gtk_label_set_use_markup (GTK_LABEL (label8), TRUE);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (vbox1), frame3, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame3), 4);

  alignment3 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (frame3), alignment3);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment3), 0, 0, 12, 0);

  table3 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (alignment3), table3);
  gtk_container_set_border_width (GTK_CONTAINER (table3), 5);
  gtk_table_set_row_spacings (GTK_TABLE (table3), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 5);

  label9 = gtk_label_new ("X:");
  gtk_widget_show (label9);
  gtk_table_attach (GTK_TABLE (table3), label9, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label9), 0, 0.5);

  label10 = gtk_label_new ("Y:");
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table3), label10, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label10), 0, 0.5);

  label11 = gtk_label_new ("Z:");
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table3), label11, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label11), 0, 0.5);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_table_attach (GTK_TABLE (table3), entry7, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_table_attach (GTK_TABLE (table3), entry8, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_table_attach (GTK_TABLE (table3), entry9, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  label12 = gtk_label_new ("New land blocks");
  gtk_widget_show (label12);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label12);
  gtk_label_set_use_markup (GTK_LABEL (label12), TRUE);

  button1 = gtk_button_new_with_mnemonic ("Generate new land");
  gtk_widget_show (button1);
  gtk_box_pack_start (GTK_BOX (vbox1), button1, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button1), 5);
  gtk_widget_add_accelerator (button1, "clicked", accel_group,
                              GDK_G, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  g_signal_connect ((gpointer) button1, "pressed",
                    G_CALLBACK (on_new_land_button1_pressed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (editor_land_new_generator, editor_land_new_generator, "editor_land_new_generator");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, Land_start, "Land_start");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, table1, "table1");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, label2, "label2");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, label3, "label3");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, label4, "label4");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, label1, "label1");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, table2, "table2");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, label5, "label5");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, label6, "label6");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, label7, "label7");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, label8, "label8");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, table3, "table3");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, label9, "label9");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, label10, "label10");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, label11, "label11");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, label12, "label12");
  GLADE_HOOKUP_OBJECT (editor_land_new_generator, button1, "button1");

  gtk_window_add_accel_group (GTK_WINDOW (editor_land_new_generator), accel_group);

  return editor_land_new_generator;
}

GtkWidget*
create_editor_land_height_map_modificator (void)
{
  GtkWidget *editor_land_height_map_modificator;
  GtkWidget *vbox2;
  GtkWidget *pixmap;
  GtkWidget *alignment4;
  GtkWidget *table4;
  GtkWidget *label14;
  GtkWidget *label27;
  GtkWidget *filechooserbutton1;
  GtkWidget *label13;
  GtkWidget *frame7;
  GtkWidget *alignment7;
  GtkWidget *table7;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *entry15;
  GtkWidget *entry16;
  GtkWidget *combobox2;
  GtkWidget *label23;
  GtkWidget *frame5;
  GtkWidget *alignment5;
  GtkWidget *table5;
  GtkWidget *checkbutton1;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *colorbutton1;
  GtkWidget *colorbutton2;
  GtkWidget *label15;
  GtkWidget *frame6;
  GtkWidget *alignment6;
  GtkWidget *table6;
  GtkWidget *checkbutton2;
  GtkWidget *label20;
  GtkWidget *button7;
  GtkWidget *label28;

  editor_land_height_map_modificator = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (editor_land_height_map_modificator), "Height map modificator");
  gtk_window_set_default_size (GTK_WINDOW (editor_land_height_map_modificator), 200, -1);
  gtk_window_set_resizable (GTK_WINDOW (editor_land_height_map_modificator), FALSE);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (editor_land_height_map_modificator), vbox2);

  pixmap = gtk_frame_new (NULL);
  gtk_widget_show (pixmap);
  gtk_box_pack_start (GTK_BOX (vbox2), pixmap, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (pixmap), 4);
  gtk_frame_set_shadow_type (GTK_FRAME (pixmap), GTK_SHADOW_ETCHED_OUT);

  alignment4 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (pixmap), alignment4);
  gtk_container_set_border_width (GTK_CONTAINER (alignment4), 4);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment4), 0, 0, 12, 0);

  table4 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table4);
  gtk_container_add (GTK_CONTAINER (alignment4), table4);

  label14 = gtk_label_new ("File:");
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (table4), label14, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  label27 = gtk_label_new ("Note: Colors are transformed\nto range (0..1) ");
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table4), label27, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  filechooserbutton1 = gtk_file_chooser_button_new ("Select A File", GTK_FILE_CHOOSER_ACTION_OPEN);
  gtk_widget_show (filechooserbutton1);
  gtk_table_attach (GTK_TABLE (table4), filechooserbutton1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label13 = gtk_label_new ("<b>Pixmap</b>");
  gtk_widget_show (label13);
  gtk_frame_set_label_widget (GTK_FRAME (pixmap), label13);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  frame7 = gtk_frame_new (NULL);
  gtk_widget_show (frame7);
  gtk_box_pack_start (GTK_BOX (vbox2), frame7, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame7), 4);
  gtk_frame_set_shadow_type (GTK_FRAME (frame7), GTK_SHADOW_ETCHED_OUT);

  alignment7 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (frame7), alignment7);
  gtk_container_set_border_width (GTK_CONTAINER (alignment7), 4);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment7), 0, 0, 12, 0);

  table7 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table7);
  gtk_container_add (GTK_CONTAINER (alignment7), table7);

  label24 = gtk_label_new ("Color multiplier:");
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table7), label24, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);

  label25 = gtk_label_new ("Color shift:");
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table7), label25, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  label26 = gtk_label_new ("Height operation:");
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table7), label26, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  entry15 = gtk_entry_new ();
  gtk_widget_show (entry15);
  gtk_table_attach (GTK_TABLE (table7), entry15, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 8226);
  gtk_entry_set_width_chars (GTK_ENTRY (entry15), 10);

  entry16 = gtk_entry_new ();
  gtk_widget_show (entry16);
  gtk_table_attach (GTK_TABLE (table7), entry16, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16), 8226);
  gtk_entry_set_width_chars (GTK_ENTRY (entry16), 10);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_table_attach (GTK_TABLE (table7), combobox2, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label23 = gtk_label_new ("<b>Height operations</b>");
  gtk_widget_show (label23);
  gtk_frame_set_label_widget (GTK_FRAME (frame7), label23);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  frame5 = gtk_frame_new (NULL);
  gtk_widget_show (frame5);
  gtk_box_pack_start (GTK_BOX (vbox2), frame5, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame5), 4);
  gtk_frame_set_shadow_type (GTK_FRAME (frame5), GTK_SHADOW_ETCHED_OUT);

  alignment5 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (frame5), alignment5);
  gtk_container_set_border_width (GTK_CONTAINER (alignment5), 4);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment5), 0, 0, 12, 0);

  table5 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table5);
  gtk_container_add (GTK_CONTAINER (alignment5), table5);

  checkbutton1 = gtk_check_button_new_with_mnemonic ("active");
  gtk_widget_show (checkbutton1);
  gtk_table_attach (GTK_TABLE (table5), checkbutton1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label16 = gtk_label_new ("Color low:");
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (table5), label16, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label16), 0, 0.5);

  label17 = gtk_label_new ("Color top:");
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table5), label17, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label17), 0, 0.5);

  colorbutton1 = gtk_color_button_new ();
  gtk_widget_show (colorbutton1);
  gtk_table_attach (GTK_TABLE (table5), colorbutton1, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  colorbutton2 = gtk_color_button_new ();
  gtk_widget_show (colorbutton2);
  gtk_table_attach (GTK_TABLE (table5), colorbutton2, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label15 = gtk_label_new ("<b>Color mask</b>");
  gtk_widget_show (label15);
  gtk_frame_set_label_widget (GTK_FRAME (frame5), label15);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  frame6 = gtk_frame_new (NULL);
  gtk_widget_show (frame6);
  gtk_box_pack_start (GTK_BOX (vbox2), frame6, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame6), 4);
  gtk_frame_set_shadow_type (GTK_FRAME (frame6), GTK_SHADOW_ETCHED_OUT);

  alignment6 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (frame6), alignment6);
  gtk_container_set_border_width (GTK_CONTAINER (alignment6), 4);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment6), 0, 0, 12, 0);

  table6 = gtk_table_new (3, 3, FALSE);
  gtk_widget_show (table6);
  gtk_container_add (GTK_CONTAINER (alignment6), table6);

  checkbutton2 = gtk_check_button_new_with_mnemonic ("active");
  gtk_widget_show (checkbutton2);
  gtk_table_attach (GTK_TABLE (table6), checkbutton2, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label20 = gtk_label_new ("<b>Area</b>");
  gtk_widget_show (label20);
  gtk_frame_set_label_widget (GTK_FRAME (frame6), label20);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);

  button7 = gtk_button_new_with_mnemonic ("Apply");
  gtk_widget_show (button7);
  gtk_box_pack_start (GTK_BOX (vbox2), button7, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button7), 4);

  label28 = gtk_label_new ("final_height = \n(color * color_multiplier + color_shift)\nHEIGHT_OPERATION current_height");
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (vbox2), label28, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button7, "pressed",
                    G_CALLBACK (on_height_map_button7_pressed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (editor_land_height_map_modificator, editor_land_height_map_modificator, "editor_land_height_map_modificator");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, pixmap, "pixmap");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, table4, "table4");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, label14, "label14");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, label27, "label27");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, filechooserbutton1, "filechooserbutton1");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, label13, "label13");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, frame7, "frame7");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, table7, "table7");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, label24, "label24");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, label25, "label25");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, label26, "label26");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, entry15, "entry15");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, entry16, "entry16");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, label23, "label23");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, frame5, "frame5");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, table5, "table5");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, label16, "label16");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, label17, "label17");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, colorbutton1, "colorbutton1");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, colorbutton2, "colorbutton2");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, label15, "label15");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, frame6, "frame6");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, table6, "table6");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, label20, "label20");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, button7, "button7");
  GLADE_HOOKUP_OBJECT (editor_land_height_map_modificator, label28, "label28");

  return editor_land_height_map_modificator;
}

GtkWidget*
create_editor_main (void)
{
  GtkWidget *editor_main;
  GtkWidget *editor_main_box;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *clear1;
  GtkWidget *separatormenuitem1;
  GtkWidget *load1;
  GtkWidget *save1;
  GtkWidget *separator3;
  GtkWidget *preferences1;
  GtkWidget *separator4;
  GtkWidget *quit1;
  GtkWidget *scene1;
  GtkWidget *scene1_menu;
  GtkWidget *view1;
  GtkWidget *view1_menu;
  GtkWidget *reset1;
  GtkWidget *move1;
  GtkWidget *rotate1;
  GtkWidget *zoom_in1;
  GtkWidget *zoom_out1;
  GtkWidget *selection1;
  GtkWidget *selection1_menu;
  GtkWidget *set1;
  GtkWidget *add1;
  GtkWidget *clear2;
  GtkWidget *mode1;
  GtkWidget *mode1_menu;
  GtkWidget *points1;
  GtkWidget *wired1;
  GtkWidget *solid1;
  GtkWidget *textured1;
  GtkWidget *tools1;
  GtkWidget *tools1_menu;
  GtkWidget *objects1;
  GtkWidget *modificators2;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *about1;
  GtkWidget *gui_box;
  GtkWidget *divider;
  GtkWidget *main_age_frame;
  GtkWidget *vbox3;
  GtkWidget *combobox_tool_type;
  GtkWidget *hseparator4;
  GtkWidget *tool_frame;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  editor_main = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (editor_main), "Editor");
  gtk_window_set_default_size (GTK_WINDOW (editor_main), 200, 600);

  editor_main_box = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (editor_main_box);
  gtk_container_add (GTK_CONTAINER (editor_main), editor_main_box);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (editor_main_box), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic ("_File");
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  clear1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_show (clear1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), clear1);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  load1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (load1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), load1);

  save1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), save1);

  separator3 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator3);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separator3);
  gtk_widget_set_sensitive (separator3, FALSE);

  preferences1 = gtk_menu_item_new_with_mnemonic ("Preferences");
  gtk_widget_show (preferences1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), preferences1);

  separator4 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator4);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separator4);
  gtk_widget_set_sensitive (separator4, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), quit1);

  scene1 = gtk_menu_item_new_with_mnemonic ("Scene");
  gtk_widget_show (scene1);
  gtk_container_add (GTK_CONTAINER (menubar1), scene1);

  scene1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (scene1), scene1_menu);

  view1 = gtk_menu_item_new_with_mnemonic ("View");
  gtk_widget_show (view1);
  gtk_container_add (GTK_CONTAINER (scene1_menu), view1);

  view1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (view1), view1_menu);

  reset1 = gtk_menu_item_new_with_mnemonic ("Reset");
  gtk_widget_show (reset1);
  gtk_container_add (GTK_CONTAINER (view1_menu), reset1);
  gtk_widget_add_accelerator (reset1, "activate", accel_group,
                              GDK_R, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  move1 = gtk_menu_item_new_with_mnemonic ("Move");
  gtk_widget_show (move1);
  gtk_container_add (GTK_CONTAINER (view1_menu), move1);
  gtk_widget_add_accelerator (move1, "activate", accel_group,
                              GDK_M, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  rotate1 = gtk_menu_item_new_with_mnemonic ("Rotate");
  gtk_widget_show (rotate1);
  gtk_container_add (GTK_CONTAINER (view1_menu), rotate1);
  gtk_widget_add_accelerator (rotate1, "activate", accel_group,
                              GDK_R, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  zoom_in1 = gtk_menu_item_new_with_mnemonic ("Zoom In");
  gtk_widget_show (zoom_in1);
  gtk_container_add (GTK_CONTAINER (view1_menu), zoom_in1);
  gtk_widget_add_accelerator (zoom_in1, "activate", accel_group,
                              GDK_KP_Add, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  zoom_out1 = gtk_menu_item_new_with_mnemonic ("Zoom Out");
  gtk_widget_show (zoom_out1);
  gtk_container_add (GTK_CONTAINER (view1_menu), zoom_out1);
  gtk_widget_add_accelerator (zoom_out1, "activate", accel_group,
                              GDK_KP_Subtract, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  selection1 = gtk_menu_item_new_with_mnemonic ("Selection");
  gtk_widget_show (selection1);
  gtk_container_add (GTK_CONTAINER (scene1_menu), selection1);

  selection1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (selection1), selection1_menu);

  set1 = gtk_menu_item_new_with_mnemonic ("Set");
  gtk_widget_show (set1);
  gtk_container_add (GTK_CONTAINER (selection1_menu), set1);

  add1 = gtk_menu_item_new_with_mnemonic ("Add");
  gtk_widget_show (add1);
  gtk_container_add (GTK_CONTAINER (selection1_menu), add1);

  clear2 = gtk_menu_item_new_with_mnemonic ("Clear");
  gtk_widget_show (clear2);
  gtk_container_add (GTK_CONTAINER (selection1_menu), clear2);

  mode1 = gtk_menu_item_new_with_mnemonic ("Mode");
  gtk_widget_show (mode1);
  gtk_container_add (GTK_CONTAINER (scene1_menu), mode1);

  mode1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (mode1), mode1_menu);

  points1 = gtk_menu_item_new_with_mnemonic ("Points");
  gtk_widget_show (points1);
  gtk_container_add (GTK_CONTAINER (mode1_menu), points1);

  wired1 = gtk_menu_item_new_with_mnemonic ("Wired");
  gtk_widget_show (wired1);
  gtk_container_add (GTK_CONTAINER (mode1_menu), wired1);

  solid1 = gtk_menu_item_new_with_mnemonic ("Solid");
  gtk_widget_show (solid1);
  gtk_container_add (GTK_CONTAINER (mode1_menu), solid1);

  textured1 = gtk_menu_item_new_with_mnemonic ("Textured");
  gtk_widget_show (textured1);
  gtk_container_add (GTK_CONTAINER (mode1_menu), textured1);

  tools1 = gtk_menu_item_new_with_mnemonic ("Tools");
  gtk_widget_show (tools1);
  gtk_container_add (GTK_CONTAINER (menubar1), tools1);

  tools1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (tools1), tools1_menu);

  objects1 = gtk_menu_item_new_with_mnemonic ("Objects");
  gtk_widget_show (objects1);
  gtk_container_add (GTK_CONTAINER (tools1_menu), objects1);
  gtk_widget_add_accelerator (objects1, "activate", accel_group,
                              GDK_1, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  modificators2 = gtk_menu_item_new_with_mnemonic ("Modificators");
  gtk_widget_show (modificators2);
  gtk_container_add (GTK_CONTAINER (tools1_menu), modificators2);
  gtk_widget_add_accelerator (modificators2, "activate", accel_group,
                              GDK_2, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  menuitem4 = gtk_menu_item_new_with_mnemonic ("_Help");
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  about1 = gtk_menu_item_new_with_mnemonic ("_About");
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), about1);

  gui_box = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (gui_box);
  gtk_box_pack_start (GTK_BOX (editor_main_box), gui_box, TRUE, TRUE, 0);

  divider = gtk_hpaned_new ();
  gtk_widget_show (divider);
  gtk_box_pack_start (GTK_BOX (gui_box), divider, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (divider), 0);

  main_age_frame = gtk_frame_new (NULL);
  gtk_widget_show (main_age_frame);
  gtk_paned_pack1 (GTK_PANED (divider), main_age_frame, TRUE, FALSE);
  gtk_frame_set_shadow_type (GTK_FRAME (main_age_frame), GTK_SHADOW_IN);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_paned_pack2 (GTK_PANED (divider), vbox3, TRUE, TRUE);
  gtk_container_set_border_width (GTK_CONTAINER (vbox3), 4);

  combobox_tool_type = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_tool_type);
  gtk_box_pack_start (GTK_BOX (vbox3), combobox_tool_type, FALSE, TRUE, 4);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_show (hseparator4);
  gtk_box_pack_start (GTK_BOX (vbox3), hseparator4, FALSE, TRUE, 4);

  tool_frame = gtk_frame_new (NULL);
  gtk_widget_show (tool_frame);
  gtk_box_pack_start (GTK_BOX (vbox3), tool_frame, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (tool_frame), GTK_SHADOW_NONE);

  g_signal_connect ((gpointer) clear1, "activate",
                    G_CALLBACK (on_clear1_activate),
                    NULL);
  g_signal_connect ((gpointer) load1, "activate",
                    G_CALLBACK (on_load1_activate),
                    NULL);
  g_signal_connect ((gpointer) save1, "activate",
                    G_CALLBACK (on_save1_activate),
                    NULL);
  g_signal_connect ((gpointer) preferences1, "activate",
                    G_CALLBACK (on_preferences1_activate),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) reset1, "activate",
                    G_CALLBACK (on_reset1_activate),
                    NULL);
  g_signal_connect ((gpointer) move1, "activate",
                    G_CALLBACK (on_move1_activate),
                    NULL);
  g_signal_connect ((gpointer) rotate1, "activate",
                    G_CALLBACK (on_rotate1_activate),
                    NULL);
  g_signal_connect ((gpointer) zoom_in1, "activate",
                    G_CALLBACK (on_zoom_in1_activate),
                    NULL);
  g_signal_connect ((gpointer) zoom_out1, "activate",
                    G_CALLBACK (on_zoom_out1_activate),
                    NULL);
  g_signal_connect ((gpointer) set1, "activate",
                    G_CALLBACK (on_set1_activate),
                    NULL);
  g_signal_connect ((gpointer) add1, "activate",
                    G_CALLBACK (on_add1_activate),
                    NULL);
  g_signal_connect ((gpointer) clear2, "activate",
                    G_CALLBACK (on_clear2_activate),
                    NULL);
  g_signal_connect ((gpointer) points1, "activate",
                    G_CALLBACK (on_points1_activate),
                    NULL);
  g_signal_connect ((gpointer) wired1, "activate",
                    G_CALLBACK (on_wired1_activate),
                    NULL);
  g_signal_connect ((gpointer) solid1, "activate",
                    G_CALLBACK (on_solid1_activate),
                    NULL);
  g_signal_connect ((gpointer) textured1, "activate",
                    G_CALLBACK (on_textured1_activate),
                    NULL);
  g_signal_connect ((gpointer) objects1, "activate",
                    G_CALLBACK (on_objects1_activate),
                    NULL);
  g_signal_connect ((gpointer) modificators2, "activate",
                    G_CALLBACK (on_modificators2_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (editor_main, editor_main, "editor_main");
  GLADE_HOOKUP_OBJECT (editor_main, editor_main_box, "editor_main_box");
  GLADE_HOOKUP_OBJECT (editor_main, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (editor_main, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (editor_main, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (editor_main, clear1, "clear1");
  GLADE_HOOKUP_OBJECT (editor_main, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (editor_main, load1, "load1");
  GLADE_HOOKUP_OBJECT (editor_main, save1, "save1");
  GLADE_HOOKUP_OBJECT (editor_main, separator3, "separator3");
  GLADE_HOOKUP_OBJECT (editor_main, preferences1, "preferences1");
  GLADE_HOOKUP_OBJECT (editor_main, separator4, "separator4");
  GLADE_HOOKUP_OBJECT (editor_main, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (editor_main, scene1, "scene1");
  GLADE_HOOKUP_OBJECT (editor_main, scene1_menu, "scene1_menu");
  GLADE_HOOKUP_OBJECT (editor_main, view1, "view1");
  GLADE_HOOKUP_OBJECT (editor_main, view1_menu, "view1_menu");
  GLADE_HOOKUP_OBJECT (editor_main, reset1, "reset1");
  GLADE_HOOKUP_OBJECT (editor_main, move1, "move1");
  GLADE_HOOKUP_OBJECT (editor_main, rotate1, "rotate1");
  GLADE_HOOKUP_OBJECT (editor_main, zoom_in1, "zoom_in1");
  GLADE_HOOKUP_OBJECT (editor_main, zoom_out1, "zoom_out1");
  GLADE_HOOKUP_OBJECT (editor_main, selection1, "selection1");
  GLADE_HOOKUP_OBJECT (editor_main, selection1_menu, "selection1_menu");
  GLADE_HOOKUP_OBJECT (editor_main, set1, "set1");
  GLADE_HOOKUP_OBJECT (editor_main, add1, "add1");
  GLADE_HOOKUP_OBJECT (editor_main, clear2, "clear2");
  GLADE_HOOKUP_OBJECT (editor_main, mode1, "mode1");
  GLADE_HOOKUP_OBJECT (editor_main, mode1_menu, "mode1_menu");
  GLADE_HOOKUP_OBJECT (editor_main, points1, "points1");
  GLADE_HOOKUP_OBJECT (editor_main, wired1, "wired1");
  GLADE_HOOKUP_OBJECT (editor_main, solid1, "solid1");
  GLADE_HOOKUP_OBJECT (editor_main, textured1, "textured1");
  GLADE_HOOKUP_OBJECT (editor_main, tools1, "tools1");
  GLADE_HOOKUP_OBJECT (editor_main, tools1_menu, "tools1_menu");
  GLADE_HOOKUP_OBJECT (editor_main, objects1, "objects1");
  GLADE_HOOKUP_OBJECT (editor_main, modificators2, "modificators2");
  GLADE_HOOKUP_OBJECT (editor_main, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (editor_main, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (editor_main, about1, "about1");
  GLADE_HOOKUP_OBJECT (editor_main, gui_box, "gui_box");
  GLADE_HOOKUP_OBJECT (editor_main, divider, "divider");
  GLADE_HOOKUP_OBJECT (editor_main, main_age_frame, "main_age_frame");
  GLADE_HOOKUP_OBJECT (editor_main, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (editor_main, combobox_tool_type, "combobox_tool_type");
  GLADE_HOOKUP_OBJECT (editor_main, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (editor_main, tool_frame, "tool_frame");

  gtk_window_add_accel_group (GTK_WINDOW (editor_main), accel_group);

  return editor_main;
}

GtkWidget*
create_editor_properties (void)
{
  GtkWidget *editor_properties;
  GtkWidget *notebook1;
  GtkWidget *empty_notebook_page;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label31;

  editor_properties = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (editor_properties), "Editor Properties");

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (editor_properties), notebook1);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label29 = gtk_label_new ("General");
  gtk_widget_show (label29);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label29);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label30 = gtk_label_new ("label30");
  gtk_widget_show (label30);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label30);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label31 = gtk_label_new ("label31");
  gtk_widget_show (label31);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label31);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (editor_properties, editor_properties, "editor_properties");
  GLADE_HOOKUP_OBJECT (editor_properties, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (editor_properties, label29, "label29");
  GLADE_HOOKUP_OBJECT (editor_properties, label30, "label30");
  GLADE_HOOKUP_OBJECT (editor_properties, label31, "label31");

  return editor_properties;
}

GtkWidget*
create_editor_land_height_fractal (void)
{
  GtkWidget *editor_land_height_fractal;
  GtkWidget *vbox5;
  GtkWidget *frame8;
  GtkWidget *alignment8;
  GtkWidget *table8;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *entry20;
  GtkWidget *entry19;
  GtkWidget *entry18;
  GtkWidget *label33;
  GtkWidget *button8;

  editor_land_height_fractal = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (editor_land_height_fractal), "Land fractal generator");

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (editor_land_height_fractal), vbox5);

  frame8 = gtk_frame_new (NULL);
  gtk_widget_show (frame8);
  gtk_box_pack_start (GTK_BOX (vbox5), frame8, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame8), 4);

  alignment8 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (frame8), alignment8);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment8), 0, 0, 12, 0);

  table8 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table8);
  gtk_container_add (GTK_CONTAINER (alignment8), table8);
  gtk_container_set_border_width (GTK_CONTAINER (table8), 3);
  gtk_table_set_row_spacings (GTK_TABLE (table8), 3);
  gtk_table_set_col_spacings (GTK_TABLE (table8), 3);

  label34 = gtk_label_new ("Range min:");
  gtk_widget_show (label34);
  gtk_table_attach (GTK_TABLE (table8), label34, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label34), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label34), 0, 0.5);

  label35 = gtk_label_new ("Range max:");
  gtk_widget_show (label35);
  gtk_table_attach (GTK_TABLE (table8), label35, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label35), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label35), 0, 0.5);

  label36 = gtk_label_new ("Hurst exponent:");
  gtk_widget_show (label36);
  gtk_table_attach (GTK_TABLE (table8), label36, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label36), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label36), 0, 0.5);

  entry20 = gtk_entry_new ();
  gtk_widget_show (entry20);
  gtk_table_attach (GTK_TABLE (table8), entry20, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry20), 8226);

  entry19 = gtk_entry_new ();
  gtk_widget_show (entry19);
  gtk_table_attach (GTK_TABLE (table8), entry19, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry19), 8226);

  entry18 = gtk_entry_new ();
  gtk_widget_show (entry18);
  gtk_table_attach (GTK_TABLE (table8), entry18, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry18), 8226);

  label33 = gtk_label_new ("<b>Fractal generator params</b>");
  gtk_widget_show (label33);
  gtk_frame_set_label_widget (GTK_FRAME (frame8), label33);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);

  button8 = gtk_button_new_with_mnemonic ("Apply");
  gtk_widget_show (button8);
  gtk_box_pack_start (GTK_BOX (vbox5), button8, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button8), 4);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (editor_land_height_fractal, editor_land_height_fractal, "editor_land_height_fractal");
  GLADE_HOOKUP_OBJECT (editor_land_height_fractal, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (editor_land_height_fractal, frame8, "frame8");
  GLADE_HOOKUP_OBJECT (editor_land_height_fractal, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (editor_land_height_fractal, table8, "table8");
  GLADE_HOOKUP_OBJECT (editor_land_height_fractal, label34, "label34");
  GLADE_HOOKUP_OBJECT (editor_land_height_fractal, label35, "label35");
  GLADE_HOOKUP_OBJECT (editor_land_height_fractal, label36, "label36");
  GLADE_HOOKUP_OBJECT (editor_land_height_fractal, entry20, "entry20");
  GLADE_HOOKUP_OBJECT (editor_land_height_fractal, entry19, "entry19");
  GLADE_HOOKUP_OBJECT (editor_land_height_fractal, entry18, "entry18");
  GLADE_HOOKUP_OBJECT (editor_land_height_fractal, label33, "label33");
  GLADE_HOOKUP_OBJECT (editor_land_height_fractal, button8, "button8");

  return editor_land_height_fractal;
}

GtkWidget*
create_menu1 (void)
{
  GtkWidget *menu1;
  GtkWidget *view2;

  menu1 = gtk_menu_new ();

  view2 = gtk_menu_item_new_with_mnemonic ("View");
  gtk_widget_show (view2);
  gtk_container_add (GTK_CONTAINER (menu1), view2);

  g_signal_connect ((gpointer) view2, "activate",
                    G_CALLBACK (on_view2_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (menu1, menu1, "menu1");
  GLADE_HOOKUP_OBJECT (menu1, view2, "view2");

  return menu1;
}

