/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_editor_land_new_generator (void);
GtkWidget* create_editor_land_height_map_modificator (void);
GtkWidget* create_editor_main (void);
GtkWidget* create_editor_properties (void);
GtkWidget* create_editor_land_height_fractal (void);
GtkWidget* create_menu1 (void);
